OOP版lsコマンド作成
2525nicole/ruby-practices pull request #12
Opened 2023-06-28 06:46 UTC by 2525nicole

## プラクティス名
[lsコマンドを作るオブジェクト指向版 \| FBC](https://bootcamp.fjord.jp/practices/213)

## コメント
OOP版lsコマンドの課題を提出いたします🙇‍♀️
ご確認の程よろしくお願いいたします！

2023-07-04 16:01 UTC, u1tnk requested changes
まずは大枠のところだけです！

2023-07-04 16:01 UTC, u1tnk commented on 08.ls_object/ls.rb
> +ls_execution_result = LsExecutionResult.new(options)
ここをメインにするかメインクラスを作って 処理の流れが分かるようにして欲しいです。
分け方もいくつかあると思いますが、大枠は以下のようになると思います。

1. ファイルリストを取得
1. ファイルの詳細情報を取得
1. 出力用の整形(空白を埋めたり並びかえたり)
1. 出力

2023-07-04 16:01 UTC, u1tnk commented on 08.ls_object/ls_execution_result.rb
> +class LsExecutionResult
「実行結果」という名前なのに実質メイン処理をやっていて file情報取得以外全部となっています。
前述した通りメイン処理をここから切り離してあとは何をやっているのか考えて名前をつけてみてください。

こちらも参考にしてください。メイン処理を切り離す理由の補足です。

[マトリョーシカ人形のようなメソッド設計を避ける - give IT a try](https://blog.jnito.com/entry/2022/11/28/072945)

2023-07-04 16:01 UTC, u1tnk commented on 08.ls_object/file_list.rb
> +class FileList
このクラスの責務が少な過ぎます。
ここに複数のファイル処理用の処理を集めて、 FileDetailsの方をファイル一つずつの処理にすればバランスが取れそうです。

2023-07-04 16:01 UTC, u1tnk commented on 08.ls_object/file_details.rb
> +class FileDetails
file_listの方に書いた理由でこちらは単数形にして、ファイル一つの情報を一インスタンスとして持つようにしてみてください。

2023-07-08 08:42 UTC, 2525nicole commented on 08.ls_object/file_details.rb
> +class FileDetails
ありがとうございます！
ご教示いただいたようにファイル一つの情報を一インスタンスとして持つように修正いたしました🙇‍♀️

2023-07-08 08:42 UTC, 2525nicole commented on 08.ls_object/file_list.rb
> +class FileList
ご教示いただいたようそれぞれのクラスの責務を修正いたしました🙏

2023-07-08 08:44 UTC, 2525nicole commented on 08.ls_object/ls.rb
> +ls_execution_result = LsExecutionResult.new(options)
具体的な例をいただきありがとうございます！
`ls.rb`をメインにしてみました🙇‍♀️

「2.ファイルの詳細情報を取得」以降の処理は`l`オプションの有無で変わってくるので、
「1.ファイルリストを取得」の処理後に条件分岐を挟んで処理を書きました。

2023-07-08 08:47 UTC, 2525nicole commented on 08.ls_object/ls_execution_result.rb
> +class LsExecutionResult
参考URLまでいただきありがとうございます🙇‍♀️
以下のように修正いたしました🙏
- メイン処理は`ls.rb`に集約
- `LsExecutionResult`クラスをなくす
- 代わりに出力（出力用の整形も含む）を行う`FileDisplay`クラスを作成

2023-07-08 16:21 UTC, u1tnk requested changes
全部こまかく見れてないですが、目についたところをコメントしたので同じようなところを含めて修正してください。
特に重要なところは各クラスの責務が明確になっていないところだと思います。

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/ls.rb
> +OPTIONS = ARGV.getopts('a', 'r', 'l')
定数は固定の値を入れるところです。
optionsは状態によって変わるので変数にしましょう。

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/ls.rb
> +  displayed_details_list = FileDisplay.new(details_and_options)
一回変数に入れるより、以下のように直接書いた方が見やすいです。

`FileDisplay.new(displayed_file_information: file_details, options: OPTIONS)`

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/ls.rb
> +if OPTIONS['l']
分岐ルートは最低限にした方が見やすいです。
Lオプションはあっても無くてもdetail用の情報取得を行なっても問題ないので表示するところだけ分岐すると全体の流れが見やすくなりますね。

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/file_display.rb
> +      @formated_file_details = format_file_details
formatted のスペルミスでしょうか？ スペルミスは無いように心配なときは辞書を引いてチェックしていきましょう。
プログラムにおいて名前はとても大事なので。

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/file_list.rb
> +      args = { file_name:, file_stat: File.lstat(file_name) }
file_statを取得する責務は FileDetailにあるべきだと思います。

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/file_list.rb
> +      file_detail_hash = FileDetail.new(args).file_detail
FileDetailからhashを取り出して使うなら `FileDetail.new(args).file_detail` はメソッドになっても変わらないです。
柔軟な対応ができるように FileDetailのインスタンス自体をFileListが持つようにしましょう。

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +    @file_name = args[:file_name]
ハッシュを渡して分解するのではなく、 `initialize(file_name:, file_stat:)` のように名前付きの引数を使いましょう。
見やすいこと、チェックしてくれることが理由です。

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +  def build_file_detail
呼び出し元でも書きましたが、hashを返すのではなく、それぞれの情報をメソッドで返すようにした方が良いですね。

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +    @file_stat.mtime.strftime('%_m %_d %R')
このクラスは情報を管理するクラスなので、フォーマットは FileDisplayに任せましょう。

2023-07-08 16:21 UTC, u1tnk commented on 08.ls_object/file_list.rb
> +  def initialize(options)
全てのclassに optionsを全部渡すのでは無く、そのクラスに必要なものだけを渡しましょう。
そのクラスが何をインプットとしているか明確にすることは何をやるか推測するにあたり重要なので。

2023-07-09 13:20 UTC, 2525nicole commented on 08.ls_object/ls.rb
> +OPTIONS = ARGV.getopts('a', 'r', 'l')
定数の定義への認識が足りてなく、余計な修正を加えておりました...
基本的なところで申し訳ありません。
修正いたしました🙇‍♀️！

2023-07-09 13:25 UTC, 2525nicole commented on 08.ls_object/file_display.rb
> +      @formated_file_details = format_file_details
重ねて基本的な部分でレビューをいただいてしまい申し訳ありません...
ご指摘いただいたとおり大事なところですので、注意いたします。
修正いたしました🙇‍♀️

2023-07-10 04:05 UTC, 2525nicole commented on 08.ls_object/ls.rb
> +  displayed_details_list = FileDisplay.new(details_and_options)
ありがとうございます！
たしかに直接書いた方が一眼でわかりますね＞＜
同様の箇所も含めて修正いたしました🙇‍♀️

2023-07-10 04:09 UTC, 2525nicole commented on 08.ls_object/ls.rb
> +if OPTIONS['l']
条件分岐後の処理を表示する処理のみに修正いたしました🙏

2023-07-10 11:34 UTC, 2525nicole commented on 08.ls_object/file_detail.rb
> +    @file_name = args[:file_name]
`initialize`の引数をハッシュから名前付きの引数を使用するよう修正いたしました🙇‍♀️
理由もありがとうございます！
キーワード引数だと渡された引数に過不足があると例外が発生するという点確認いたしました🙏

2023-07-10 11:46 UTC, 2525nicole commented on 08.ls_object/file_list.rb
> +  def initialize(options)
理由も併せてご教示いただきありがとうございます🙇‍♀️
以下のように修正いたしました🙏
- `FileDisplay`クラスに全optionsを渡していた記述
  - 不要になったため削除
- `FileList`クラスに全optionsを渡していた記述
  - 渡す必要がないため`l`オプションを渡す処理を削除

2023-07-10 11:53 UTC, 2525nicole commented on 08.ls_object/file_list.rb
> +      args = { file_name:, file_stat: File.lstat(file_name) }
`FileDetails`クラスの責務になるよう修正いたしました🙇‍♀️

2023-07-10 12:15 UTC, 2525nicole commented on 08.ls_object/file_detail.rb
> +  def build_file_detail
FileDetailsクラスから`build_file_detail`をなくし、FileList側でメソッドの結果をハッシュとして持つような処理に修正いたしました🙇‍♀️

2023-07-10 12:20 UTC, 2525nicole commented on 08.ls_object/file_list.rb
> +      file_detail_hash = FileDetail.new(args).file_detail
提出したコードではFileListがFileDetailsのインスタンス自体を持っていないこと、今回のレビューで気がつきました🙏
（`file_detail_hash`はあくまでFileDetails内の`file_details`ハッシュを参照した結果を変数に格納しているだけと解釈しました👀）

以下のようにコードを修正いたしました🙇‍♀️
- `FileDetail.new(file_name: file_name)`のインスタンスを変数`file_detail`に格納
- FileDetailのインスタンス`file_detail`からそれぞれの情報をメソッドで呼び出してハッシュに格納する

2023-07-10 12:35 UTC, 2525nicole commented on 08.ls_object/file_detail.rb
> +    @file_stat.mtime.strftime('%_m %_d %R')
ご指摘のとおりFileDisplayに任せるのが適切でした🙇‍♀️
修正いたしました！

2023-07-10 12:36 UTC, 2525nicole commented on 08.ls_object/ls.rb
> +if OPTIONS['l']
Lオプションによる条件分岐を表示メソッドの分岐のみに修正いたしました🙇‍♀️

2023-07-10 16:05 UTC, u1tnk requested changes

2023-07-10 16:05 UTC, u1tnk commented on 08.ls_object/displayed_file_information.rb
> +    @file_names = file_names
file_detailがfile_nameを持っているはずなので detailsだけで良いと思います。

2023-07-10 16:05 UTC, u1tnk commented on 08.ls_object/file_list.rb
> +    file_details_array = []
ruby界隈では 複数形はもう配列なので _arrayは消しましょう。_array/_listなどはほぼ見ないです。
また、慣れているとfile_detailsという変数名で、FileDetailというクラスがあるということは「FileDetailのインスタンスの配列な！」と判断しますので、今回の場合はhashが入っていて混乱するのでよくないのです。

更に、前回 FileDetailからhashを返していましたが、今回はここでhashにしてインスタンスを捨てているのでもうちょっとです。
ここでやっているようなことを DisplayedFileInformation クラスが出力するときにやれば良いです。

例えば出力する情報が一つ増えたときに出力処理とFile Detailクラスだけを修正すれば良いところ、hashを挟んでいるとこの処理も変更が必要になります。
単純に変更量が多いという他にFileListクラスがFileDetailの内容に依存してしまうのも良くないですね。

2023-07-10 16:05 UTC, u1tnk commented on 08.ls_object/file_list.rb
> +    @file_names_list = build_file_names_list
ここも後述した通り、file_detailがfile_nameを持っているので二重で持つ必要がないです。
データが二重になるとどちらかだけ変更してしまうバグの原因になります。

2023-07-10 16:05 UTC, u1tnk commented on 08.ls_object/displayed_file_information.rb
> +    file_details_hash = @file_details
これはもともとのhashの順番に出力が依存しているので実質、 file_listのhash作成処理が順番を制御していて依存しているのは良くないです

2023-07-12 23:54 UTC, 2525nicole commented on 08.ls_object/displayed_file_information.rb
> +    @file_names = file_names
`DisplayedFileFormatter`（DisplayedFileInformationから名前を変更しました！）のインスタンスがfile_nameを持たないように修正いたしました🙇‍♀️

2023-07-13 00:01 UTC, 2525nicole commented on 08.ls_object/file_list.rb
> +    file_details_array = []
>ruby界隈では 複数形はもう配列なので _arrayは消しましょう。_array/_listなどはほぼ見ないです。
`_list`という変数名にしていたところを複数形に修正しました。
（ls.rb内のfile_listはFileListのインスタンスの配列のため、file_listといった変数名のままにしています。）

>ここでやっているようなことを DisplayedFileInformation クラスが出力するときにやれば良いです。
理由も詳細に教えていただきありがとうございます！ご教示いただいたとおり、DisplayedFileFormatter（DisplayedFileInformationから名前を変更）で行うよう修正いたしました🙇‍♀️

2023-07-13 00:02 UTC, 2525nicole commented on 08.ls_object/file_list.rb
> +    @file_names_list = build_file_names_list
file_listがfile_nameを持たないように修正いたしました🙏

2023-07-13 00:08 UTC, 2525nicole commented on 08.ls_object/displayed_file_information.rb
> +    file_details_hash = @file_details
ご指摘ありがとうございます！
以下のように修正し、解消できているかと思うのですが、いかがでしょうか🙏
ご確認をお願いいたします🙇‍♀️

- ハッシュの作成をDisplayedFileFormatter（DisplayedFileInformationから名前を変更）の出力時に行う
- 出力時のformatも同時に行う

2023-07-13 15:38 UTC, u1tnk commented on 08.ls_object/file_list.rb
> +    file_details_array = []
> （ls.rb内のfile_listはFileListのインスタンスの配列のため、file_listといった変数名のままにしています。）

はい、これは問題ありません  🙆‍♀️

2023-07-13 16:08 UTC, u1tnk requested changes

2023-07-13 16:08 UTC, u1tnk commented on 08.ls_object/displayed_file_formatter.rb
> +    @file_details.map do |file_detail|
戻り値を必要としないときは mapではなくeachを使うべきです。

2023-07-13 16:08 UTC, u1tnk commented on 08.ls_object/displayed_file_formatter.rb
> +          hardlink: file_detail.obtain_hardlink_number.rjust(find_max_size(@file_details.map(&:obtain_hardlink_number))),
find_max_sizeは不要かと思います。以下二つと大差は無いかと思います。


```
@file_details.map(&:obtain_hardlink_number).map(&:size).max
```
```
@file_details.map{_1.obtain_hardlink_number.size}.max
```

もしくは file_details はこのインスタンスに持ってるわけなので 、以下ぐらいになるならメソッドあっても良いと思います。
```
find_max_size(:obtain_hardlink_number))`
```

2023-07-13 16:08 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +  require 'etc'
[修正するほどじゃないけど気になった]
require は classの上に書くのが一般的…とは思いますが rubocopも文句言わないならそんなに気にしなくても良いか…と思いました。

2023-07-13 16:08 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +    FileTest.symlink?(@file_name) ? "#{@file_name} -> #{File.readlink(@file_name)}" : @file_name
こういう処理はあっても良いかなとも思うのですが、名前とあってないのは気になりますね。
とはいえ正確に表現しようとすると長くなりすぎそうだし、

`symlink?`メソッドとfile_name/symlink メソッドを作って、Formatter側で分岐した方が分かりやすいかと思いましっが。

2023-07-13 16:08 UTC, u1tnk commented on 08.ls_object/ls.rb
> +if options['l']
今のようにFormatterが一つなら `options['l']` もFormatterに渡して、内部で分岐する方が良いと思います。

Lオプション用のFormatterと通常のFormatterを分けるならここで分岐しても良いですね。

2023-07-13 23:56 UTC, 2525nicole commented on 08.ls_object/displayed_file_formatter.rb
> +    @file_details.map do |file_detail|
ありがとうございます🙇‍♀️該当の2箇所修正いたしました！

2023-07-13 23:59 UTC, 2525nicole commented on 08.ls_object/file_detail.rb
> +  require 'etc'
ご教示いただきありがとうございます！
たしかにrubocopからの指摘はなかったのですが、
一般的な書き方とのことでrequireをclassの上に移動いたしました🙏

2023-07-14 04:18 UTC, 2525nicole commented on 08.ls_object/ls.rb
> +if options['l']
ありがとうございます🙇‍♀️
二つの考え方を教えていただき勉強になります。
Formatterを一つのまま、`options['l']`を渡して内部で分岐するように修正いたしました🙏

2023-07-14 11:57 UTC, 2525nicole commented on 08.ls_object/file_detail.rb
> +    FileTest.symlink?(@file_name) ? "#{@file_name} -> #{File.readlink(@file_name)}" : @file_name
ありがとうございます！
`obtain_symlink`は名前のとおりシンボリックリンクの取得のみの処理を持たせ、
Formatter側で条件分岐とシンボリックリンク有無の表示内容とフォーマット処理を行なうようにいたしました🙏

2023-07-14 12:20 UTC, 2525nicole commented on 08.ls_object/displayed_file_formatter.rb
> +          hardlink: file_detail.obtain_hardlink_number.rjust(find_max_size(@file_details.map(&:obtain_hardlink_number))),
以下の形で呼び出せるよう`find_max_size`メソッドを修正いたしました🙇‍♀️

> もしくは file_details はこのインスタンスに持ってるわけなので 、以下ぐらいになるならメソッドあっても良いと思います。
```
find_max_size(:obtain_hardlink_number)
```

2023-07-15 15:09 UTC, u1tnk requested changes

2023-07-15 15:09 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +  def obtain_block_number
ちょっと遅い指摘ですみませんが、 obtain無しで `file_detail.block_number` のように呼ぶとスッキリして良いですね。
メソッドは基本的には動詞ですが、読み出して返すだけのようなメソッドは名詞にするのが一般的です。

2023-07-15 15:09 UTC, u1tnk commented on 08.ls_object/ls.rb
> +displayed_files = DisplayedFileFormatter.new(file_details:, l_option: options['l'])
流れがスッキリしましたね！

と、スッキリしたので分かったのですが、 file_listは file_detailsを持っているのでここで渡すのはfile_listで良いですね。

2023-07-15 15:09 UTC, u1tnk commented on 08.ls_object/displayed_file_formatter.rb
> +  def calc_total_blocks
ここらへんの 複数のファイルからデータを計算したり取得する処理は file_listにあるべきです。

2023-07-16 02:06 UTC, 2525nicole commented on 08.ls_object/file_detail.rb
> +  def obtain_block_number
>メソッドは基本的には動詞ですが、読み出して返すだけのようなメソッドは名詞にするのが一般的です。

そうなのですね！ご教示いただきありがとうございます🙇‍♀️
おかげさまでobtainを省略することができ、スッキリしました！

2023-07-16 03:39 UTC, 2525nicole commented on 08.ls_object/displayed_file_formatter.rb
> +  def calc_total_blocks
ありがとうございます！
たしかにcalc_total_blocksは表示に関する処理ではなく、複数のファイルからデータを計算する処理でした🙇‍♀️
file_listに移動いたしました。

2023-07-16 13:51 UTC, 2525nicole commented on 08.ls_object/ls.rb
> +displayed_files = DisplayedFileFormatter.new(file_details:, l_option: options['l'])
おかげさまでだいぶスッキリしました🙇‍♀️
ご丁寧にレビューいただきありがとうございます！

>file_listは file_detailsを持っているのでここで渡すのはfile_listで良いですね。
たしかに...！ls.rb内でfile_detailsに代入して渡す必要はありませんでした🙇‍♀️
file_listを渡すように修正いたしました🙏

2023-07-17 15:43 UTC, u1tnk requested changes

2023-07-17 15:43 UTC, u1tnk commented on 08.ls_object/displayed_file_formatter.rb
> +  def find_max_size(symbol = nil)
ここはやっぱりFileListの方が良いかなと思います。
フォーマットの為のデータではありますが、ファイルリストの情報を集計して取得するデータなので所属としてはFileListになると思います。

2023-07-18 14:31 UTC, 2525nicole commented on 08.ls_object/displayed_file_formatter.rb
> +  def find_max_size(symbol = nil)
ありがとうございます🙇‍♀️
悩んでいた点なので、理由も併せてご教示いただきスッキリしました！
FileListで行うよう修正いたしました🙏

2023-07-18 15:17 UTC, u1tnk approved these changes
formatterの max_size消したいところでしたが、消しちゃうとかなり冗長になるという理由は分かるので良しとします！ 🙆‍♀️

2023-07-18 23:36 UTC, merged