first commit
2525nicole/ruby-practices pull request #2
Opened 2022-09-02 14:31 UTC by 2525nicole

## プラクティス名
カレンダーのプログラム(ruby)

## コメント
カレンダーのプログラム(ruby)を作成いたしました。
ご確認をお願いいたします。

2022-09-07 08:51 UTC, func09 requested changes

2022-09-07 08:51 UTC, func09 commented on 02.calendar/cal.rb
> +year = ARGV[1] || Date.today.year
[MUST] `ruby cal.rb -y 2020 -m 8` こんな感じで
yとmの引数の順番によってはエラーになるようです。

2022-09-07 08:51 UTC, func09 commented on 02.calendar/cal.rb
> +print header.center(20) + "\n"
[nits] わざわざ変数にいれなくても出力できそうですね。
改行ありで出力するなら `puts` を使ってよいと思います。

```suggestion
puts "#{month}月 #{year}".center(20)
```

2022-09-07 08:51 UTC, func09 commented on 02.calendar/cal.rb
> +  print " "+day_of_week.join(" ") + "\n"
```suggestion
print " "+day_of_week.join(" ") + "\n"
```

[nits] 不要なインデントを削除しましょう

2022-09-07 08:51 UTC, func09 commented on 02.calendar/cal.rb
> +First_day = Date.new(year.to_i, month.to_i, 1)
```suggestion
first_day = Date.new(year.to_i, month.to_i, 1)
```

[MUST] 変数名の最初の文字を大文字にしてよいのは定数（クラス名やモジュール名など）だけにしましょう。

2022-09-07 08:51 UTC, func09 commented on 02.calendar/cal.rb
> +end
```suggestion
print "   " * First_day.wday
```

[nits] `String#*` で文字列を繰り返すことができます。こういうところで使うのがおすすめです。

2022-09-07 08:51 UTC, func09 commented on 02.calendar/cal.rb
> +    print " " + "\e[30;47m#{date_display}\e[0m" + "\n"
👍

2022-09-07 08:51 UTC, func09 commented on 02.calendar/cal.rb
> +end
[IMO] 「今日だったら反転する」と「土曜日だったら改行する」という条件を
ひとつのケース式で分岐する必要はなく
別々の条件として考えてあげると、分岐がスッキリすると思います。

それから `Date#saturday?` というメソッドで土曜日かどうか判定できますので
それを使うのも良いと思います。

```suggestion
days_of_the_month.each do |day|
  date_display = day.day.to_s.rjust(2)
  if day == Date.today
    print " " + "\e[30;47m#{date_display}\e[0m"
  else
    print " " + date_display
  end
  print "\n" if day.saturday?
end
```

2022-09-12 06:45 UTC, 2525nicole commented on 02.calendar/cal.rb
> +end
@func09 
レビューありがとうございます！
以下、修正いたしました。お手数をおかけしますがご確認をお願いいたします🙇‍♀️

## 修正した点
### [MUST]
- yとmの引数の順番によって発生するエラーを解消
- First_dayの頭文字を小文字に（変数に）
  - 「月初日はどの年月でも1日である」から定数にしてしまっていましたが、改めてコードを確認すると`Date.new(year.to_i, month.to_i, 1)`のyearとmonthは引数で指定した数字が代入される=呼び出しごとに変わる、ことから変数が適切であると気づきました。

### [MUST]以外
-  年月の表示
  - 変数の使用をやめた
  - `print`→`puts`に変更
- 不要なインデントの削除
- 繰り返し処理を`n.times`から`String#*`に修正
- 「今日だったら反転する」と「土曜日だったら改行する」という条件を別々の条件とした分岐に修正
  - `Date#saturday?`メソッドを使用

2022-09-12 09:51 UTC, func09 approved these changes
LGTMです〜

2022-09-12 13:19 UTC, 2525nicole commented
@func09 
ありがとうございます！！
マージいたします🙇‍♀️！！

2022-09-12 13:21 UTC, merged